### ISSUE TITLE
`Create message -> Run -> get messages` pipeline is riddled with issues.

### ISSUE THREAD

**Issue by CakeCrusher** [stellar-amenities/hal-9100#78]
In my project the following endpoint consistently fails on assistants but succeeds in OpenAI assistants:
https://github.com/CakeCrusher/opengpts-monorepo/blob/c6f71b8c1ae8be91ffe8cdea4906ae104c811424/backend/app/routers/thread_router.py#L109-L178

This endpoint depends on:
- assistant with code interpreter
- basic thread
- user (has no effect with run)

When I run with content that forces it to use code interpreter, it fails:
 "Please solve [1 2 3;4 5 6] x [7 8;9 10;11 12]. Make sure to run the code first using code interpreter."

This basic pipeline needs to get troubleshooted.

**Comment by louis030195** [comment]
What is the error? What LLM do you use? Most use cases are tested with mixtral 7b 8 so lower performance LLMs might not work

**Comment by CakeCrusher** [comment]
Used LLM `gpt-3.5-turbo`, will get back to you with more info later.

**Comment by AkshatGiri** [comment]
Noticed similar issues with mixtral-8x7b-instruct

**Comment by louis030195** [comment]
@AkshatGiri can you provide any details? What did run, what are the logs, etc. anything would be helpful, thanks!

**Comment by louis030195** [comment]
Closing issue due to lack of specificity
