### ISSUE TITLE
When can we expect the release?

### ISSUE THREAD

**Issue by dacom-dark-sun** [stellar-amenities/hal-9100#79]
Hi guys! You are doing a good job. We already use an open source alternative to Openai (OpenOpenAI), but it is not being developed. Tell me, when can we expect a more or less stable release that would replicate the standard functionality of the chatbot? Now we see your active development and therefore we are in no hurry to integrate. Maybe make a release with a stable tag?

**Comment by louis030195** [comment]
@dacom-dark-sun what is your definition of stable?

I'm solo maintainer atm, feel free to check issues :)
