### ISSUE TITLE
Missing field `id`

### ISSUE THREAD

**Issue by FingerLiu** [stellar-amenities/hal-9100#96]
**Describe the bug**
The quickstart shows error.

start server
```
make docker
make server
make consumer
```

and then run quickstart.ipynb
```
main()
```

consumer log show this error
```
ERROR hal_9100_extra::llm] Error calling OpenAI API: Deserialization Error: missing field `id` at line 8 column 1
```

<img width="1372" alt="image" src="https://github.com/stellar-amenities/hal-9100/assets/3981064/99b85048-1da5-4e21-a86f-90ed12944eb9">

**Comment by louis030195** [comment]
Which LLM API are you using? This happens either when the LLM API is not OpenAI compatible or there was an error (rate limit or something). Error handling can probably be improved there

**Comment by FingerLiu** [comment]
I added some log, and it shows that my OpenAI token is invalid, after change token, it works!
